# fly.toml app configuration file generated for node-demo on 2023-11-20T18:01:46+01:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "node-demo"
primary_region = "ams"

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
